### PR TITLE
Fixed --environment command-line option

### PR DESCRIPTION
**Pull request by SPDoctor**
#### Category
- [ ] New Feature
- [ ] New Framework
- [x ] Bugfix
- [ ] Documentation fixed

#### What's in this Pull Request?

Fixes that were preventing the --environment command line variable from working, and also causing a hang if an invalid input value for the --environment command line variable

### CODE REVIEW

**Comment by StfBauer** [comment]
Have you tried to run ’npm test’?

**Comment by SPDoctor** [comment]
Yes, all passing. Tested the fix as well.

**Comment by StfBauer** [comment]
Cool thanks wonder why it haven't been discovered by those tests.

**Comment by SPDoctor** [comment]
I think the typo in the name meant it didn't do anything. Once I fixed that I discovered the hang on invalid value for the parameter. It was also defaulting to a Boolean type instead of string type, so it could never work properly - just suppressing the packages prompt but not changing the options. I presume it also wouldn't pass the environment value through to the underlying generator-sharepoint, although I admit I didn't check whether it was passed through after the fix.

**Comment by SPDoctor** [comment]
I suppose I should have written a failing test first ;-). Fact of the matter is I thought I was just fixing a typo in the help text. I ended up getting in way deeper than I expected.

**Comment by StfBauer** [comment]
There is just less than 1% that probably use this option to pass in command line options. 
The switches were first introduced in version 1.6.2. Before that is was only a simple pass-through option directly to the SPFx generator.

I guess in that version it was only a pass-through also but the SPFx option only took action.

Thank you for fixing @SPDoctor - Your help is always welcome.

**Comment by SPDoctor** [comment]
You could argue you don't really need the command-line option, but then you have to be consistent with the generator-sharepoint. And maybe somebody might need to call it from some uber-script.

**Pull request merged**
