### PR TITLE
Add Aurelia WebPart to SPO and SP2019

### PR DESCRIPTION
**Pull request by magnusdanielson**
#### Category
- [x] New Feature
- [ ] New Framework
- [ ] Bugfix
- [ ] Documentation fixed
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Added the option to select Aurelia Framework and implemented the template for Webparts, SharePoint2019 and SharePoint Online.

### CODE REVIEW

**Comment by StfBauer** [comment]
Can you also add some documentation around the generator?
Thank you!!!

**Comment by magnusdanielson** [comment]
I have now updated the documentation and added the fix for spfx 1.10.0. I just noticed there is a conflict in package-lock.json. I am hubmle about my knowledge how to fix that in a correct way. What is the next step now?

**Comment by StfBauer** [comment]
@magnusdanielson forget about the conflict ;) I will handle it. Let me check your changes.

**Comment by StfBauer** [comment]
PR merged manual - Thank you very much @magnusdanielson

**Pull request closed without merging**
