### PR TITLE
upgraded devops pipeline definition to node 10 and other minor improvements

### PR DESCRIPTION
**Pull request by baywet**
#### Category
- [ ] New Feature
- [ ] New Framework
- [ ] Bugfix
- [ ] Documentation fixed
- Related issues: 

#### What's in this Pull Request?
- upgraded to node 10 for pipeline definition (spfx 1.8.2 brings support)
- other minor fixes in pipeline definition

### CODE REVIEW

**Comment by StfBauer** [comment]
Can you add a selection on which version of NodeJS is running, please?
Potentially you break the NodeJS 8 version.
To check the NodeJS version:
https://nodejs.org/docs/v0.10.12/api/process.html#process_process_version

Thank you.

**Comment by baywet** [comment]
@StfBauer this is going to change the nodejs version installed on the azure devops machine during build time. This is not going to impact the local installation.
Project should be compatible with it as long as it's spfx 1.8.2 and above.
I don't think we should constrain the version of nodejs used on the build system to the version used by one developer on the team.
Additionally, support for nodejs 8 will be dropped in future releases, this is also a way of being future-proof.
What do you think?

**Comment by StfBauer** [comment]
@baywet Got ya! Haven't thought about that.

**Comment by StfBauer** [comment]
Thank you @baywet once again.

**Pull request merged**
