### PR TITLE
Fix for camel case issue

### LINKED ISSUE #131: Some templates seems use wrong names
#### General Information
* [x] Bug

Under `util.deployTemplates`: 
```javascript
const ejsInject = {
	componentClassName: component.componentClassName,
	componentClassNameKebabCase: paramCase(component.componentClassName),
	componentNameCamelCase: component.componentClassName, // <-- this one is not correct
	componentStrings: component.componentClassName + 'Strings',
	componentPath: component.componentPath,
	componentName: component.componentName
};
```  

According to its name, `componentNameCamelCase` should be initialized with something like `camelCase(component.componentName)`    
SPFx uses camel case component name transformation in scss files, but code above injects `componentClassName` instead in scss files which is not correct.

### PR DESCRIPTION
**Pull request by s-KaiNet**
#### Category
- [ ] New Feature
- [ ] New Framework
- [x] Bugfix
- [ ] Documentation fixed
- Related issues: Fixes #131

### CODE REVIEW

**Comment by StfBauer** [comment]
lodash already has a function so there is no need for another camelCase function.
see the documentation: https://lodash.com/docs/4.17.11#camelCase

**Comment by s-KaiNet** [comment]
Yep, I haven't noticed lodash in deps. However, this PR seems irrelevant, because we can't change the value of `componentNameCamelCase` because of the [bug](https://github.com/SharePoint/sp-dev-docs/issues/2481) in SPFx.

**Comment by StfBauer** [comment]
Please also make sure style lint is configured to support SuiteCSS because this is what SPFx uses as naming conventions.
[https://github.com/suitcss](https://github.com/suitcss)

**Comment by s-KaiNet** [comment]
@StfBauer Are you sure it uses SuiteCSS?   

> The component's name must be written in pascal case. Nothing else in the HTML/CSS uses pascal case.

Checkout OOB `HelloWorld.module.scss`:   

```css
.helloWorld {....
```  

that's not a Pascal case.   

> ComponentName--modifierName  

I haven't found anything similar to this in OOB SPFx styles.

**Pull request closed without merging**
